# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13e0c20a9c3845fbf41a085e979aaab1"
name = "Pushnova"
application_url = "https://pushnova.fly.dev/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"              mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://int.pushnova.app/compliance.php"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"] 
uri = "/webhooks/app_subscriptions/update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"


[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "https://int.pushnova.app/orders.php"

# checkouts/create → Google Pub/Sub (same topic or a different one if you prefer)
[[webhooks.subscriptions]]
topics = ["checkouts/create"]
uri = "https://int.pushnova.app/checkout.php"

[access_scopes]

# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_app_proxy,write_app_proxy,read_checkouts,read_orders,write_products,read_themes,"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://pushnova.fly.dev/auth/callback"]
[app_proxy]
url = "https://int.pushnova.app"
subpath = "notify"
prefix = "apps"
